### ISSUE TITLE
About EVT

### ISSUE THREAD

**Issue by garronej** [dldc-packages/pubsub#5]
Hey salut, 

Je parle en français parce que j'ai vu sur ton profil que tu étais Français et parisien comme moi. 🇫🇷 
Je suis tombé sur ton projet en regardant les `using` de `denoify`.  

Je sais que ce n'est pas vraiment de bon ton de parler d'un projet similaire dans les issues, mais là nos deux modules sont tellement similaires que je me permets de te signaler l'existence d'[EVT](https://evt.land).

Si tu as des retours ou suggestions je suis toute ouis. 

 Bye :octocat:

**Comment by etienne-dldc** [comment]
Hello,

Merci pour `denoify`, le projet est top !
Je connaissais déjà `evt` même si je l'ai découvert après avoir développé `suub`.

Bien que les deux projets ont des similarités, je reste convaincu qu'ils ne répondent pas aux mêmes besoins et qu'il ont donc tous les deux leur place dans l'écosystème.

La différence principale entre les deux projets c'est le scope:
- `suub` est volontairement simple, l'intégralité du code tiens dans un unique fichier et il n'y a aucune dépendance externe.
- `suub` est également bien plus limité en termes de fonctionnalités et j'ai porté une attention particulière à [gérer tous les cas particuliers](https://github.com/etienne-dldc/suub#some-precisions) auquel j'ai pu penser.

Grâce à ce scope limité `suub` est environ 20x plus léger que `evt` (voir [evt sur bundlephobia](https://bundlephobia.com/result?p=evt@1.9.4) et [Suub sur bundlephobia](https://bundlephobia.com/result?p=suub@3.1.2))

**Comment by garronej** [comment]
Je crois qu'on s'es mal compris.  

Je n'étais pas entrain de suggéré de kill ton projet, bien sûr il y a de la place pour tout le monde!  

C'est juste que je me disais que ça pouvait t'intéresser de voir l'approche d'EVT sur différents points. 
Comme j'ai trouvé intéressant de regarder l'API de SUUB pour comprendre les usecases que tu as trouvé judicieux de mettre en avant. 

Salut
